<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Default.aspx.cs" Inherits="PongR.Default" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
        <style>
        * {
            margin: 0px;
            padding: 0px;
            background-color: black;
        }

        canvas {
            background-color: white;
            display: block;
            margin: 0px auto;
            border-top: 20px solid orange;
            border-bottom: 20px solid orange;
            border-left: 20px solid gray;
            border-right: 20px solid gray;
            width: 800px;
            height: 450px;
        }

        ul {
            margin-top: 20px;
            width: 200px;
            height: 100px;
            margin-left: auto;
            margin-right: auto;
        }
    </style>
</head>
<body>
    <ul>
        <li><a href="Default.aspx?Player=1">Jogador 1</a></li>
        <li><a href="Default.aspx?Player=2">Jogador 2</a></li>
    </ul>

    <canvas id="game"></canvas>
    <!--Script references. -->
    <!--Reference the jQuery library. -->
    <script src="Scripts/jquery-1.10.2.min.js"></script>
    <!--Reference the SignalR library. -->
    <script src="Scripts/jquery.signalR-2.0.2.min.js"></script>
    <!--Reference the autogenerated SignalR hub script. -->
    <script src="signalr/hubs"></script>
    <!--Add script to update the page and send messages.-->
    <script src="PongGame.js"></script>

    <% if (!string.IsNullOrEmpty(RetrievePlayer())) { %>

    <script>

        function CaptureInput() {
            var pongGame = $.connection.pongGameHub;
            
            if (keys[38]) {
                pongGame.server.move<%= RetrievePlayer() %>Up();
            }

            if (keys[40]) {
                pongGame.server.move<%= RetrievePlayer() %>Down();
            }
        }

        $(function () {
            NewGame();
        });

    </script>

    <% } %>

</body>
</html>
