<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Default.aspx.cs" Inherits="PongR.Default" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
        <style>
        * {
            margin: 0px;
            padding: 0px;
        }

        canvas {
            display: block;
            margin: 0px auto;
            border: 1px solid #000;
        }
    </style>
</head>
<body>
    <canvas id="game"></canvas>
    <!--Script references. -->
    <!--Reference the jQuery library. -->
    <script src="Scripts/jquery-1.10.2.min.js"></script>
    <!--Reference the SignalR library. -->
    <script src="Scripts/jquery.signalR-2.0.2.min.js"></script>
    <!--Reference the autogenerated SignalR hub script. -->
    <script src="signalr/hubs"></script>
    <!--Add script to update the page and send messages.-->
    <script src="PongGame.js"></script>

    <script>

        //event listener
        function MouseMove(e) {
            var pongGame = $.connection.pongGameHub;
            var vPos = e.pageY - <%= RetrievePlayer() %>.Height / 2;

            pongGame.server.move<%= RetrievePlayer() %>(vPos)
        }

        $(function () {
            NewGame();
        });

    </script>
</body>
</html>
